server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true    
  tomcat:
    uri-encoding: UTF-8
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: test
      password: 1234    
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/instagram?useUnicode=true
    username: root
    password: toor
    
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file: # 프로젝트 내의 변수로 사용
 path: C:\Learn\fileupload\